Repository PROxZIMA/DarkSpider, pull requests merged in 2022-08, with the labels that each got.

#9 Fix: Ignore Gooey installation by default
  .gitignore
  torcrawl.py
Labels: bug

#11 Add: CLI command to include/exclude external links
  README.md
  modules/crawler.py
  torcrawl.py
Labels: bug, documentation, enhancement

#10 Fixed Issue related to Graphical Analysis
  demo.json
  graph.png
  indegree_bar.png
  indegree_plot.png
  modules/visualization.py
  outdegree_bar.png
  outdegree_plot.png
Labels: enhancement

#14 Creating json
  modules/crawler.py
Labels: enhancement

#16 Added 'exclusion' Argument
  README.md
  modules/crawler.py
  torcrawl.py
Labels: enhancement

#13 Added required functionalities and Images
  README.md
  modules/crawler.py
  modules/visualization.py
  torcrawl.py
Labels: enhancement

#7 White box unit test cases for modules
  modules/crawler.py
  modules/extractor.py
  modules/helpers/__init__.py
  modules/helpers/helper.py
  modules/tests/__init__.py
  modules/tests/test_checker.py
  modules/tests/test_crawler.py
  modules/tests/test_extractor.py
  modules/tests/test_visualization.py
  modules/visualization.py
  res/keywords.yar
Labels: documentation
